# workflow by Naupaka Zimmerman nzimmerman@usfca.edu
# November 7, 2022

on: [push, pull_request]

name: Check final project

jobs:
  docker:
    runs-on: ubuntu-latest
    container: rocker/verse
    steps:
      - uses: actions/checkout@v4
      - name: Install Package and other Dependencies
        run: |-
          Rscript -e "install.packages('remotes', repos = 'https://packagemanager.rstudio.com/all/__linux__/focal/latest')"
          Rscript -e "install.packages('lintr', repos = 'https://packagemanager.rstudio.com/all/__linux__/focal/latest')"
          Rscript -e "remotes::install_deps(dependencies = TRUE, repos = 'https://packagemanager.rstudio.com/all/__linux__/focal/latest')"
          apt update && apt install shellcheck
      - name: Render all Rmarkdown files
        run: |-
          Rscript -e "lapply(list.files(pattern = 'Rmd|rmd', recursive = TRUE), rmarkdown::render)"
      - name: lint all Rmarkdown files and R scripts
        run: |-
          R -f tests/lint_r_rmarkdown_files.R
      - name: Run shellcheck on all bash scripts
        run: |-
          for file in $(find . -type f -name "*.sh"); do shellcheck $file; done;
      - name: Check for spaces in filenames
        run: |-
          if [ $(find . | grep -E '\s|\*|\?|\$|%' | wc -l) -gt 0 ]; \
            then echo "Spaces found in filenames"; find . | grep -E '\s|\*|\?|\$|%'; exit 1; fi
